sudo: false
language: elixir
elixir:
  - 1.7
  - 1.7.3
otp_release:
  - 21.0
  - 21.0.7
script:
  - "MIX_ENV=test mix deps.get --force"
  - "MIX_ENV=test mix deps.compile --force"
  - "MIX_ENV=test mix compile --force --warnings-as-errors"
  - "MIX_ENV=test mix format --check-formatted --dry-run"
  - "MIX_ENV=test mix coveralls.json --no-start"
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  recipients:
    - randy@heroictek.com
